This project is for classification of three kinds of people from X-Ray of the rib-cage.
1. Normal healthy persons (0)
2. Patients with Pneumonia (1)
3. Patients with COVID-19 (2)

Step 1: Download the dataset from shared URLS
(Only if the dataset is not downloaded already)



In [1]:
import urllib.request
import os

files = os.listdir('.')

if not "training.zip" in files:
  urllib.request.urlretrieve("https://storage.googleapis.com/psiket/bcde6d7698eb/data/training.zip?GoogleAccessId=oltau-training%40oldo-228016.iam.gserviceaccount.com&Expires=1000000000000000&Signature=XYskZa2iYp9eRxWwnOiM2q6xRyshq2Ly8j6q1kKeIkGqD8sR1KJXNUdxeVHq2GwLTPq98FW75WfUrww%2FdXcVpxxNYL%2FZF54zVC4yjJqOmwX%2FdjfFHyXqNobBcwrQf0dchyv4ElybUyO6MCLULxnzg5w9HgmG2CVG7bsB1ab5n3HoPR%2BqV5LQ2BfS2ddOEtYuQpLoLkolFWov4sdFSnDIkoUIEmSTAWuYftvJTUdiV3qSHn9mRKze8e2Vsbv0Vt54QxoqZBAFhz%2Bjy2N1uS6%2FfqhjYKPiYz2W0%2BGIXNL5FCZez9L8DaPP0KNQef6rKxvwP4ouk8O5tYkwrxLJDb0gcQ%3D%3D","training.zip")
  print("File 'training.zip' downloaded")
else:
  print("File 'training.zip' already exists")


File 'training.zip' downloaded


Step 2 Unzip the downloaded zip files (Only if the dataset is not unzipped already)

Note: Uncomment the following cell if you are running the notebook for the second time in this colab session.

* Uncomment the following shell if you are running the file for the second time

(This will delet the directory tree created for training)

In [ ]:
# %%bash
# rm training/train_data/0/*
# rmdir training/train_data/0
# rm training/train_data/1/*
# rmdir training/train_data/1
# rm training/train_data/2/*
# rmdir training/train_data/2
# rmdir training/train_data

# rm training/val_data/0/*
# rmdir training/val_data/0
# rm training/val_data/1/*
# rmdir training/val_data/1
# rm training/val_data/2/*
# rmdir training/val_data/2
# rmdir training/val_data

# rm training/test_data/0/*
# rmdir training/test_data/0
# rm training/test_data/1/*
# rmdir training/test_data/1
# rm training/test_data/2/*
# rmdir training/test_data/2
# rmdir training/test_data
# rmdir training

In [2]:
from zipfile import ZipFile
from os import path
if path.exists('training') and path.isdir('training'):
  print('The training file is already unzipped')
else:
  with ZipFile('training.zip', 'r') as zipObj:
    # Get a list of all archived file names from the zip
    zipObj.extractall('training')
    print('Training folder extracted')

Training folder extracted


Now we move our training, testing and validation data into three separate folders

In [ ]:
import numpy as np
import shutil
data_0 = os.listdir('training/train_data/0')
data_1 = os.listdir('training/train_data/1')
data_2 = os.listdir('training/train_data/2')
if not os.path.exists('training/val_data'):
  os.mkdir('training/val_data')
if not os.path.exists('training/val_data/0'):
  os.mkdir('training/val_data/0')
if not os.path.exists('training/val_data/1'):
  os.mkdir('training/val_data/1')
if not os.path.exists('training/val_data/2'):
  os.mkdir('training/val_data/2')
if not os.path.exists('training/test_data'):
  os.mkdir('training/test_data')
if not os.path.exists('training/test_data/0'):
  os.mkdir('training/test_data/0')
if not os.path.exists('training/test_data/1'):
  os.mkdir('training/test_data/1')
if not os.path.exists('training/test_data/2'):
  os.mkdir('training/test_data/2')
np.random.shuffle(data_0)
n0 = len(data_0)
for k in range(0,round(0.15*n0)):
  src = 'training/train_data/0/'+data_0[k]
  dest = 'training/val_data/0/'+data_0[k]
  shutil.move(src,dest)
for k in range(round(0.15*n0),round(0.3*n0)):
  src = 'training/train_data/0/'+data_0[k]
  dest = 'training/test_data/0/'+data_0[k]
  shutil.move(src,dest)

np.random.shuffle(data_1)
n1 = len(data_1)
for k in range(0,round(0.15*n1)):
  src = 'training/train_data/1/'+data_1[k]
  dest = 'training/val_data/1/'+data_1[k]
  shutil.move(src,dest)
for k in range(round(0.15*n1),round(0.3*n1)):
  src = 'training/train_data/1/'+data_1[k]
  dest = 'training/test_data/1/'+data_1[k]
  shutil.move(src,dest)

np.random.shuffle(data_2)
n2 = len(data_2)
for k in range(0,round(0.15*n2)):
  src = 'training/train_data/2/'+data_2[k]
  dest = 'training/val_data/2/'+data_2[k]
  shutil.move(src,dest)
for k in range(round(0.15*n2),round(0.3*n2)):
  src = 'training/train_data/2/'+data_2[k]
  dest = 'training/test_data/2/'+data_2[k]
  shutil.move(src,dest)

In [ ]:
tr_0 = os.listdir('training/train_data/0')
tr_1 = os.listdir('training/train_data/1')
tr_2 = os.listdir('training/train_data/2')
val_0 = os.listdir('training/val_data/0')
val_1 = os.listdir('training/val_data/1')
val_2 = os.listdir('training/val_data/2')
test_0 = os.listdir('training/test_data/0')
test_1 = os.listdir('training/test_data/1')
test_2 = os.listdir('training/test_data/2')
print(len(tr_0),len(tr_1),len(tr_2))
print(len(val_0),len(val_1),len(val_2))
print(len(test_0),len(test_1),len(test_2))

3903 2671 140
2031 1390 73
2032 1390 73


Step 3: We created a pre-processing block for the images. It is observed that when the images are pre-processed, the performance slightly enhences. The pre-processing stage highlights the edges of the image through a process similar to unsharp masking. The steps include:
* Find the edges of the images using a custom spatial high pass filter
* Perform gamma correction of the filtered image to improve the contrast
* Superimpose the filtered image (2D) upon the original image (3D)

Finally, the image is resized according to the specified size.

In [ ]:
import numpy as np
import cv2
import os
def adjust_gamma(image, gamma=1.0):
	# build a lookup table mapping the pixel values [0, 255] to
	# their adjusted gamma values
	invGamma = 1.0 / gamma
	table = np.array([((i / 255.0) ** invGamma) * 255
		for i in np.arange(0, 256)]).astype("uint8")
	# apply gamma correction using the lookup table
	return cv2.LUT(image, table)
 
def rotate_image(image, angle):
  image_center = tuple(np.array(image.shape[1::-1]) / 2)
  rot_mat = cv2.getRotationMatrix2D(image_center, angle, 1.0)
  result = cv2.warpAffine(image, rot_mat, image.shape[1::-1], flags=cv2.INTER_LINEAR)
  return result

def distort_image(im):
    # give a random zoom to every image (maximum 20 pixel)
    rz = np.random.randint(0,21)
    [m,n,h] = im.shape
    im2 = cv2.resize(im, (m+rz, n+rz))
    im3 = im2[round(rz/2):round(rz/2)+m,round(rz/2):round(rz/2)+m,:]
    # randomly flip some images
    if np.random.rand(1)>0.5:
        im3 = cv2.flip(im3,1)
    # give a random rotation to some of the images
    if np.random.rand(1)>0.5:
      ang = np.random.randint(-90,91)
      im3 = rotate_image(im3,ang)
    return im3

def load_images_from_folder(folder, xsize, ysize, batch_size=0, distort = False):
    all_files = os.listdir(folder)
    if batch_size > 0 and batch_size < len(all_files):
      np.random.shuffle(all_files)
      all_files = all_files[:batch_size]
    images = np.zeros([len(all_files),xsize,ysize,3])
    cnt = 0
    for filename in all_files:
        img1 = cv2.imread(os.path.join(folder,filename))
        if img1 is not None:
          img2 = adjust_gamma(img1,gamma=1.7)
          img_resized=cv2.resize(img2, (xsize,ysize))
          if distort:
            img_dist = distort_image(img_resized)
            images[cnt] = img_dist.astype('float32')/255.0
          else:
            images[cnt] = img_resized.astype('float32')/255.0
          cnt+=1
    return images

Since our RAM is limited, we decided not to load the entire dataset at once. The size of the features are very small and resizing the images degrades the quality significantly. Hence, a custom data generator is used. The following section creates the custom data generator.

We know that a datagenerator should return the data iteratively and hence the we use the keyword "yield" instead of "return". Another data generator function (datagen_static) is written which is not iterative. The purpose of this function is to generate a static set of data for validation and/or testing as required.

In [ ]:
from sklearn.utils import shuffle
from tensorflow.keras.utils import to_categorical
xsize, ysize = 299,299
# iterative data generator
def generator(base_path, batch_size=64, distort = False):
  global xsize, ysize
  n0 = round(batch_size*0.58)
  n1 = round(batch_size*0.39)
  n2 = round(batch_size*0.03)
  while n0+n1+n2 > batch_size:
    n0-=1
  while True:
    img_0 = load_images_from_folder(os.path.join(base_path,'0'),xsize,ysize,batch_size=n0, distort=distort)
    img_1 = load_images_from_folder(os.path.join(base_path,'1'),xsize,ysize,batch_size=n1, distort=distort)
    img_2 = load_images_from_folder(os.path.join(base_path,'2'),xsize,ysize,batch_size=n2, distort=distort)
    images = np.concatenate((img_0, img_1, img_2), axis=0)
    labels = to_categorical(np.concatenate((np.zeros(n0), np.ones(n1), 2*np.ones(n2))), 3)
    X_train, Y_train = shuffle(images, labels)
    yield X_train, Y_train

In [ ]:
w0, w1, w2 = 1/(3*0.58), 1/(3*0.39), 1/(3*0.03)

Now let's load tensorflow and keras packages to create the Sequential CNN model

In [ ]:
import tensorflow
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Dropout, Conv2D, AveragePooling2D, MaxPooling2D, Flatten, Activation, GlobalAveragePooling2D, BatchNormalization, Input
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.applications import VGG16,InceptionV3,ResNet50, MobileNetV2
from tensorflow.keras.optimizers import Adam

Load the Inception V2 imagenet as base model

In [ ]:
basemodel = InceptionV3(weights="imagenet", include_top=False,input_tensor=Input(shape=(xsize, ysize, 3)))

In [ ]:
n = len(basemodel.layers)
nt = 20 # number of layers to train
for k in range(n-nt):
  basemodel.layers[k].trainable = False

In [ ]:
headModel = basemodel.output
headModel = AveragePooling2D(pool_size=(2, 2))(headModel)
headModel = Flatten(name="flatten")(headModel)
headModel = Dropout(0.5)(headModel)
headModel = Dense(181, activation="relu")(headModel)
headModel = Dropout(0.3)(headModel)
headModel = Dense(3, activation="softmax")(headModel)

Compile the model

In [ ]:
model = Model(inputs=basemodel.input, outputs=headModel)

In [ ]:
 model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 299, 299, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 149, 149, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 149, 149, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 149, 149, 32) 0           batch_normalization[0][0]        
_______________________________________________________________________________________

Define a model check point to programmatically save the model whenever the validation accuracy is the minimum.

In [ ]:
epochs= 200
lr = 1e-4

In [ ]:
model.compile(loss="categorical_crossentropy", optimizer=Adam(lr=1e-4,decay=lr/epochs),metrics=["accuracy"])

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
mc = ModelCheckpoint('best_model.h5', monitor='val_loss', mode='min', verbose=1, save_best_only=True)

In [ ]:
train_gen = generator('training/train_data',batch_size=128, distort = True)
val_gen = generator('training/val_data', batch_size=128, distort = False)

Start training the model (Don't run this without a GPU)

In [ ]:
history = model.fit(train_gen, #train_images, train_labels,
                    steps_per_epoch = 10,
                    epochs=epochs,
                    verbose=2,
                    validation_data=val_gen,
                    validation_steps=5,
                    class_weight = {0: w0, 1: w1, 2: w2},
                    callbacks=[mc])

Epoch 1/200

Epoch 00001: val_loss improved from inf to 0.39859, saving model to best_model.h5
10/10 - 20s - loss: 1.2062 - accuracy: 0.5453 - val_loss: 0.3986 - val_accuracy: 0.8453
Epoch 2/200

Epoch 00002: val_loss did not improve from 0.39859
10/10 - 18s - loss: 0.7800 - accuracy: 0.7242 - val_loss: 0.4617 - val_accuracy: 0.8500
Epoch 3/200

Epoch 00003: val_loss improved from 0.39859 to 0.34430, saving model to best_model.h5
10/10 - 18s - loss: 0.5946 - accuracy: 0.7727 - val_loss: 0.3443 - val_accuracy: 0.8687
Epoch 4/200

Epoch 00004: val_loss improved from 0.34430 to 0.31670, saving model to best_model.h5
10/10 - 19s - loss: 0.5620 - accuracy: 0.7688 - val_loss: 0.3167 - val_accuracy: 0.8703
Epoch 5/200

Epoch 00005: val_loss did not improve from 0.31670
10/10 - 17s - loss: 0.5146 - accuracy: 0.8031 - val_loss: 0.3704 - val_accuracy: 0.8406
Epoch 6/200

Epoch 00006: val_loss did not improve from 0.31670
10/10 - 17s - loss: 0.5308 - accuracy: 0.7820 - val_loss: 0.3392 - val_accu

In [ ]:
from tensorflow.keras.models import load_model
test_images, test_labels = next(generator('training/test_data',batch_size=1000))
print('With best model')
best_model = load_model('best_model.h5')
score = best_model.evaluate(test_images, test_labels, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

print('With final model')
score1 = model.evaluate(test_images, test_labels, verbose=0)
print('Test loss:', score1[0])
print('Test accuracy:', score1[1])

With best model
Test loss: 0.28517624735832214
Test accuracy: 0.9129999876022339
With final model
Test loss: 0.2750973403453827
Test accuracy: 0.906000018119812


In [ ]:
from sklearn.metrics import confusion_matrix
y_true = np.argmax(test_labels,axis=-1)
pred_vals = best_model.predict(test_images)
pred_labels = np.argmax(pred_vals, axis=-1)
c = confusion_matrix(y_true,pred_labels)
print(c)
print(y_true[0:10])

[[538  41   1]
 [ 33 353   4]
 [  3   5  22]]
[1 0 0 2 0 2 0 2 1 0]
